import re
from typing import List, Set
from app.models.schemas import ClaimVerification, Citation

LEGAL_STOPWORDS: Set[str] = {
    "which", "their", "there", "these", "those", "shall", "under", "other",
    "about", "after", "where", "being", "order", "could", "would", "should",
    "every", "first", "second", "third", "accordance", "hereby", "thereof",
    "within", "without", "before", "between", "having", "either", "neither"
}

class CitationEntailmentVerifier:
    """
    Validates that claims generated by LLM reasoning are supported by statutory citations.
    Calculates entailment overlap, statutory token alignment, and section reference matching.
    """

    @staticmethod
    def verify(claim: str, citations: List[Citation]) -> ClaimVerification:
        if not citations or not claim.strip():
            return ClaimVerification(
                claim=claim,
                is_supported=False,
                confidence_score=0.0,
                supporting_citations=[]
            )

        claim_lower = claim.lower()
        claim_content_words = {
            w for w in re.findall(r'\b[a-z]{4,}\b', claim_lower)
            if w not in LEGAL_STOPWORDS
        }

        matched_citations = []
        max_score = 0.0

        for c in citations:
            verbatim_lower = c.verbatim_quote.lower()
            statute_content_words = {
                w for w in re.findall(r'\b[a-z]{4,}\b', verbatim_lower)
                if w not in LEGAL_STOPWORDS
            }

            # Check section token match (e.g., "3(p)", "rule 158b", "section 7")
            clean_section = c.section.lower().replace("section", "").replace("rule", "").replace(" ", "").strip()
            section_mentioned = bool(clean_section and (clean_section in claim_lower.replace(" ", "")))

            # Substantive term overlap
            overlap = len(claim_content_words.intersection(statute_content_words))
            ratio = overlap / max(len(claim_content_words), 1)

            if section_mentioned or ratio >= 0.20:
                score = min(1.0, 0.70 + (0.30 * ratio) + (0.10 if section_mentioned else 0.0))
                max_score = max(max_score, score)
                matched_citations.append(c)

        is_supported = len(matched_citations) > 0

        return ClaimVerification(
            claim=claim,
            is_supported=is_supported,
            confidence_score=round(max_score if is_supported else 0.0, 2),
            supporting_citations=matched_citations
        )

# Backward-compatible alias
CitationVerifier = CitationEntailmentVerifier
