import re
from typing import List, Dict, Any
from app.models.schemas import ClaimVerification, Citation

class CitationEntailmentVerifier:
    """
    Validates that claims generated by LLM reasoning are supported by statutory citations.
    Calculates entailment overlap and statutory token alignment.
    """

    @staticmethod
    def verify(claim: str, citations: List[Citation]) -> ClaimVerification:
        if not citations:
            return ClaimVerification(
                claim=claim,
                is_supported=False,
                confidence_score=0.0,
                supporting_citations=[]
            )

        claim_lower = claim.lower()
        claim_words = set(re.findall(r'\b\w{4,}\b', claim_lower))
        if not claim_words:
            return ClaimVerification(
                claim=claim,
                is_supported=False,
                confidence_score=0.0,
                supporting_citations=[]
            )

        matched_citations: List[Citation] = []
        max_score = 0.0

        for c in citations:
            verbatim_lower = c.verbatim_quote.lower()
            statute_words = set(re.findall(r'\b\w{4,}\b', verbatim_lower))
            
            overlap = len(claim_words.intersection(statute_words))
            ratio = overlap / max(len(claim_words), 1)
            
            if ratio >= 0.20:
                matched_citations.append(c)
                max_score = max(max_score, min(0.75 + ratio * 0.25, 1.0))

        is_supported = len(matched_citations) > 0

        return ClaimVerification(
            claim=claim,
            is_supported=is_supported,
            confidence_score=round(max_score if is_supported else 0.0, 2),
            supporting_citations=matched_citations
        )

# Alias for backward compatibility
CitationVerifier = CitationEntailmentVerifier
