import re
from typing import List, Dict, Any
from app.models.schemas import ClaimVerification, Citation

class CitationEntailmentVerifier:
    """
    Validates that claims generated by LLM reasoning are supported by statutory citations.
    Calculates entailment overlap and statutory token alignment.
    """

    @staticmethod
    def verify(claim: str, citations: List[Citation]) -> ClaimVerification:
        if not citations:
            return ClaimVerification(
                claim=claim,
                is_supported=False,
                confidence_score=0.0,
                supporting_citations=[]
            )

        claim_lower = claim.lower()
        supported = False
        max_score = 0.0

        for c in citations:
            section_token = c.section.lower().replace("section", "").replace(" ", "").strip()
            verbatim_lower = c.verbatim_quote.lower()
            
            claim_words = set(re.findall(r'\b\w{4,}\b', claim_lower))
            statute_words = set(re.findall(r'\b\w{4,}\b', verbatim_lower))
            
            overlap = len(claim_words.intersection(statute_words))
            ratio = overlap / max(len(claim_words), 1)
            
            if ratio >= 0.20 or (section_token and section_token in claim_lower):
                supported = True
                max_score = max(max_score, min(0.75 + ratio * 0.25, 1.0))

        return ClaimVerification(
            claim=claim,
            is_supported=supported,
            confidence_score=round(max_score if supported else 0.0, 2),
            supporting_citations=citations if supported else []
        )

# Alias for backward compatibility
CitationVerifier = CitationEntailmentVerifier
